"""新增对话人格表与头像开关

Revision ID: 09b8dbbe982a
Revises: d2a89321228e
Create Date: 2026-06-08 21:33:21.643971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b8dbbe982a'
down_revision: Union[str, None] = 'd2a89321228e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('avatar_key', sa.String(length=512), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_personas_is_active'), 'agent_personas', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_personas_user_id'), 'agent_personas', ['user_id'], unique=False)
    op.add_column('agent_configs', sa.Column('show_avatar', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'show_avatar')
    op.drop_index(op.f('ix_agent_personas_user_id'), table_name='agent_personas')
    op.drop_index(op.f('ix_agent_personas_is_active'), table_name='agent_personas')
    op.drop_table('agent_personas')
    # ### end Alembic commands ###
