"""persona_groups表+agent_personas加in_group_only

Revision ID: 115eb519d14d
Revises: 5ca36380b3f0
Create Date: 2026-06-14 15:09:34.084146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '115eb519d14d'
down_revision: Union[str, None] = '5ca36380b3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('member_persona_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enable_tools', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_groups_user_id'), 'persona_groups', ['user_id'], unique=False)
    # agent_personas 加 in_group_only：先 server_default 回填存量行，再清除默认
    op.add_column(
        'agent_personas',
        sa.Column('in_group_only', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('agent_personas', 'in_group_only', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_personas', 'in_group_only')
    op.drop_index(op.f('ix_persona_groups_user_id'), table_name='persona_groups')
    op.drop_table('persona_groups')
    # ### end Alembic commands ###
