"""create tool_configs table

Revision ID: 2307490b0a25
Revises: 78d133beb913
Create Date: 2026-06-06 00:30:13.725632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2307490b0a25'
down_revision: Union[str, None] = '78d133beb913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_key', sa.String(length=128), nullable=False),
    sa.Column('tool_type', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tool_key', name='uq_tool_user_key')
    )
    op.create_index(op.f('ix_tool_configs_tool_key'), 'tool_configs', ['tool_key'], unique=False)
    op.create_index(op.f('ix_tool_configs_user_id'), 'tool_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_configs_user_id'), table_name='tool_configs')
    op.drop_index(op.f('ix_tool_configs_tool_key'), table_name='tool_configs')
    op.drop_table('tool_configs')
    # ### end Alembic commands ###
