"""add songs.playable

Revision ID: 252ffcda08e1
Revises: 0674bf974270
Create Date: 2026-06-06 16:50:53.928825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252ffcda08e1'
down_revision: Union[str, None] = '0674bf974270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('playable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'playable')
    # ### end Alembic commands ###
