"""notify_channels 推送渠道表 + agent_tasks.notify_enabled

Revision ID: 2628f0e24602
Revises: 45e5059b4825
Create Date: 2026-06-20 23:29:10.565379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2628f0e24602'
down_revision: Union[str, None] = '45e5059b4825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notify_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('target_encrypted', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notify_channels_enabled'), 'notify_channels', ['enabled'], unique=False)
    op.create_index(op.f('ix_notify_channels_user_id'), 'notify_channels', ['user_id'], unique=False)
    op.add_column('agent_tasks', sa.Column('notify_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_tasks', 'notify_enabled')
    op.drop_index(op.f('ix_notify_channels_user_id'), table_name='notify_channels')
    op.drop_index(op.f('ix_notify_channels_enabled'), table_name='notify_channels')
    op.drop_table('notify_channels')
    # ### end Alembic commands ###
