"""conversations加群聊字段 messages加sender_persona_id

Revision ID: 31176cc42a17
Revises: 8b9b786d9b53
Create Date: 2026-06-13 00:00:40.717423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31176cc42a17'
down_revision: Union[str, None] = '8b9b786d9b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # is_group 加非空列：先给 server_default 让存量行回填 false，再清除默认（新行由 ORM 控制）
    op.add_column(
        'conversations',
        sa.Column('is_group', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('conversations', 'is_group', server_default=None)
    op.add_column('conversations', sa.Column('member_persona_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_conversations_is_group'), 'conversations', ['is_group'], unique=False)
    op.add_column('messages', sa.Column('sender_persona_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender_persona_id')
    op.drop_index(op.f('ix_conversations_is_group'), table_name='conversations')
    op.drop_column('conversations', 'member_persona_ids')
    op.drop_column('conversations', 'is_group')
    # ### end Alembic commands ###
