"""users 加 briefing_seen_at 简报已读基准

Revision ID: 45e5059b4825
Revises: 9d2abf6b960b
Create Date: 2026-06-20 23:07:05.586064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e5059b4825'
down_revision: Union[str, None] = '9d2abf6b960b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('briefing_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'briefing_seen_at')
    # ### end Alembic commands ###
