"""conversations加群聊工具开关enable_tools

Revision ID: 5ca36380b3f0
Revises: 31176cc42a17
Create Date: 2026-06-13 00:35:46.782753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca36380b3f0'
down_revision: Union[str, None] = '31176cc42a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # enable_tools 非空列：先给 server_default 让存量行回填 false，再清除默认
    op.add_column(
        'conversations',
        sa.Column('enable_tools', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('conversations', 'enable_tools', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'enable_tools')
    # ### end Alembic commands ###
