"""agent_traces+agent_spans Tracing 数据底座

Revision ID: 6727223d45f9
Revises: b8d195cf3e7a
Create Date: 2026-06-27 12:22:45.339014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6727223d45f9'
down_revision: Union[str, None] = 'b8d195cf3e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('task_name', sa.String(length=256), nullable=True),
    sa.Column('root_span_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cached_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_cny', sa.Float(), nullable=False),
    sa.Column('models_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loop_run_id', sa.UUID(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_loop_run_id'), 'agent_traces', ['loop_run_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_started_at'), 'agent_traces', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_traces_status'), 'agent_traces', ['status'], unique=False)
    op.create_index(op.f('ix_agent_traces_task_id'), 'agent_traces', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_task_type'), 'agent_traces', ['task_type'], unique=False)
    op.create_index(op.f('ix_agent_traces_trace_id'), 'agent_traces', ['trace_id'], unique=True)
    op.create_index(op.f('ix_agent_traces_user_id'), 'agent_traces', ['user_id'], unique=False)
    op.create_index('ix_agent_traces_user_started', 'agent_traces', ['user_id', 'started_at'], unique=False)
    op.create_table('agent_spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('span_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_cny', sa.Float(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('iteration_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['agent_traces.trace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_spans_iteration_id'), 'agent_spans', ['iteration_id'], unique=False)
    op.create_index(op.f('ix_agent_spans_parent_span_id'), 'agent_spans', ['parent_span_id'], unique=False)
    op.create_index(op.f('ix_agent_spans_span_id'), 'agent_spans', ['span_id'], unique=True)
    op.create_index(op.f('ix_agent_spans_span_type'), 'agent_spans', ['span_type'], unique=False)
    op.create_index(op.f('ix_agent_spans_status'), 'agent_spans', ['status'], unique=False)
    op.create_index(op.f('ix_agent_spans_trace_id'), 'agent_spans', ['trace_id'], unique=False)
    op.create_index('ix_agent_spans_trace_started', 'agent_spans', ['trace_id', 'started_at'], unique=False)
    op.create_index('ix_agent_spans_type_status', 'agent_spans', ['span_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_spans_type_status', table_name='agent_spans')
    op.drop_index('ix_agent_spans_trace_started', table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_trace_id'), table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_status'), table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_span_type'), table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_span_id'), table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_parent_span_id'), table_name='agent_spans')
    op.drop_index(op.f('ix_agent_spans_iteration_id'), table_name='agent_spans')
    op.drop_table('agent_spans')
    op.drop_index('ix_agent_traces_user_started', table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_user_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_trace_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_task_type'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_task_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_status'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_started_at'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_loop_run_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    # ### end Alembic commands ###
