"""create message_feedbacks table

Revision ID: 78d133beb913
Revises: 88b4f7f8cf58
Create Date: 2026-06-05 23:51:44.948468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d133beb913'
down_revision: Union[str, None] = '88b4f7f8cf58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_id', name='uq_feedback_user_message')
    )
    op.create_index(op.f('ix_message_feedbacks_conversation_id'), 'message_feedbacks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_feedbacks_message_id'), 'message_feedbacks', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_feedbacks_user_id'), 'message_feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_feedbacks_user_id'), table_name='message_feedbacks')
    op.drop_index(op.f('ix_message_feedbacks_message_id'), table_name='message_feedbacks')
    op.drop_index(op.f('ix_message_feedbacks_conversation_id'), table_name='message_feedbacks')
    op.drop_table('message_feedbacks')
    # ### end Alembic commands ###
