"""新增知识库表 + documents/images 加 kb_id

Revision ID: 8440c3519b07
Revises: 09b8dbbe982a
Create Date: 2026-06-12 15:55:54.348951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8440c3519b07'
down_revision: Union[str, None] = '09b8dbbe982a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_is_default'), 'knowledge_bases', ['is_default'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_user_id'), 'knowledge_bases', ['user_id'], unique=False)
    op.add_column('documents', sa.Column('kb_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_documents_kb_id'), 'documents', ['kb_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['kb_id'], ['id'], ondelete='CASCADE')
    op.add_column('images', sa.Column('kb_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_images_kb_id'), 'images', ['kb_id'], unique=False)
    op.create_foreign_key(None, 'images', 'knowledge_bases', ['kb_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_index(op.f('ix_images_kb_id'), table_name='images')
    op.drop_column('images', 'kb_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_kb_id'), table_name='documents')
    op.drop_column('documents', 'kb_id')
    op.drop_index(op.f('ix_knowledge_bases_user_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_is_default'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
