"""skill add enabled

Revision ID: 8b9b786d9b53
Revises: 9596cfc27bc1
Create Date: 2026-06-12 23:10:49.607901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9b786d9b53'
down_revision: Union[str, None] = '9596cfc27bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 加列给 server_default=true（存量技能默认显示），随后清除默认由 ORM 控制
    op.add_column(
        'skills',
        sa.Column(
            'enabled', sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    op.alter_column('skills', 'enabled', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'enabled')
    # ### end Alembic commands ###
