"""create emotion tables

Revision ID: 935266f63718
Revises: 0301daa19c01
Create Date: 2026-06-06 02:10:26.602549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '935266f63718'
down_revision: Union[str, None] = '0301daa19c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dominant_emotion', sa.String(length=32), nullable=False),
    sa.Column('avg_valence', sa.Float(), nullable=False),
    sa.Column('avg_arousal', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_emotion_profile_user')
    )
    op.create_index(op.f('ix_emotion_profiles_user_id'), 'emotion_profiles', ['user_id'], unique=False)
    op.create_table('emotion_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('emotion_type', sa.String(length=32), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('valence', sa.Float(), nullable=False),
    sa.Column('arousal', sa.Float(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trigger', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_records_created_at'), 'emotion_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_emotion_records_emotion_type'), 'emotion_records', ['emotion_type'], unique=False)
    op.create_index(op.f('ix_emotion_records_user_id'), 'emotion_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotion_records_user_id'), table_name='emotion_records')
    op.drop_index(op.f('ix_emotion_records_emotion_type'), table_name='emotion_records')
    op.drop_index(op.f('ix_emotion_records_created_at'), table_name='emotion_records')
    op.drop_table('emotion_records')
    op.drop_index(op.f('ix_emotion_profiles_user_id'), table_name='emotion_profiles')
    op.drop_table('emotion_profiles')
    # ### end Alembic commands ###
