"""share add avatars

Revision ID: 9596cfc27bc1
Revises: d429ecd1d3a9
Create Date: 2026-06-12 22:59:21.586620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9596cfc27bc1'
down_revision: Union[str, None] = 'd429ecd1d3a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_shares', sa.Column('user_avatar', sa.Text(), nullable=True))
    op.add_column('conversation_shares', sa.Column('ai_avatar', sa.Text(), nullable=True))
    op.add_column('conversation_shares', sa.Column('ai_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_shares', 'ai_name')
    op.drop_column('conversation_shares', 'ai_avatar')
    op.drop_column('conversation_shares', 'user_avatar')
    # ### end Alembic commands ###
