"""report_shares 报告分享表

Revision ID: 9d2abf6b960b
Revises: e004fbfb8ac6
Create Date: 2026-06-20 22:55:47.095591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d2abf6b960b'
down_revision: Union[str, None] = 'e004fbfb8ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_shares_is_active'), 'report_shares', ['is_active'], unique=False)
    op.create_index(op.f('ix_report_shares_report_id'), 'report_shares', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_shares_share_token'), 'report_shares', ['share_token'], unique=True)
    op.create_index(op.f('ix_report_shares_user_id'), 'report_shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_shares_user_id'), table_name='report_shares')
    op.drop_index(op.f('ix_report_shares_share_token'), table_name='report_shares')
    op.drop_index(op.f('ix_report_shares_report_id'), table_name='report_shares')
    op.drop_index(op.f('ix_report_shares_is_active'), table_name='report_shares')
    op.drop_table('report_shares')
    # ### end Alembic commands ###
