"""agent_configs 加 human_mode 全局真人模式

Revision ID: bf7ad4190462
Revises: 2628f0e24602
Create Date: 2026-06-21 00:33:04.407574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7ad4190462'
down_revision: Union[str, None] = '2628f0e24602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('human_mode', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'human_mode')
    # ### end Alembic commands ###
