"""群成员表+消息sender_user_id+会话join_code

Revision ID: ce4a6722698a
Revises: 115eb519d14d
Create Date: 2026-06-14 16:14:47.844618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4a6722698a'
down_revision: Union[str, None] = '115eb519d14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_group_member')
    )
    op.create_index(op.f('ix_group_members_conversation_id'), 'group_members', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.add_column('conversations', sa.Column('join_code', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_conversations_join_code'), 'conversations', ['join_code'], unique=False)
    op.add_column('messages', sa.Column('sender_user_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender_user_id')
    op.drop_index(op.f('ix_conversations_join_code'), table_name='conversations')
    op.drop_column('conversations', 'join_code')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_conversation_id'), table_name='group_members')
    op.drop_table('group_members')
    # ### end Alembic commands ###
