"""agent config add enable_active_recall

Revision ID: cf7ae75691ea
Revises: 3b74e7025aee
Create Date: 2026-06-12 21:28:02.930490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7ae75691ea'
down_revision: Union[str, None] = '3b74e7025aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 加列时给 server_default=true，让存量行默认开启主动记忆；随后清除默认由 ORM 控制
    op.add_column(
        'agent_configs',
        sa.Column(
            'enable_active_recall',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    op.alter_column('agent_configs', 'enable_active_recall', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'enable_active_recall')
    # ### end Alembic commands ###
