"""add users.nickname and play_histories

Revision ID: d2a89321228e
Revises: 3dffbe27b7d7
Create Date: 2026-06-07 12:27:35.005913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a89321228e'
down_revision: Union[str, None] = '3dffbe27b7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('song_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_histories_played_at'), 'play_histories', ['played_at'], unique=False)
    op.create_index(op.f('ix_play_histories_user_id'), 'play_histories', ['user_id'], unique=False)
    op.add_column('users', sa.Column('nickname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    op.drop_index(op.f('ix_play_histories_user_id'), table_name='play_histories')
    op.drop_index(op.f('ix_play_histories_played_at'), table_name='play_histories')
    op.drop_table('play_histories')
    # ### end Alembic commands ###
