"""agent config add enable_cross_session

Revision ID: db88b5cfcf7b
Revises: cf7ae75691ea
Create Date: 2026-06-12 21:53:58.490422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db88b5cfcf7b'
down_revision: Union[str, None] = 'cf7ae75691ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 加列给 server_default=false（默认关），存量行不受影响；随后清除默认由 ORM 控制
    op.add_column(
        'agent_configs',
        sa.Column(
            'enable_cross_session',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column('agent_configs', 'enable_cross_session', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'enable_cross_session')
    # ### end Alembic commands ###
