"""create agent_tasks table

Revision ID: e004fbfb8ac6
Revises: 979c6e3c897f
Create Date: 2026-06-18 23:55:57.696752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e004fbfb8ac6'
down_revision: Union[str, None] = '979c6e3c897f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('kb_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('trigger_time', sa.String(length=8), nullable=True),
    sa.Column('trigger_weekday', sa.Integer(), nullable=True),
    sa.Column('trigger_interval_hours', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_enabled'), 'agent_tasks', ['enabled'], unique=False)
    op.create_index(op.f('ix_agent_tasks_next_run_at'), 'agent_tasks', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_agent_tasks_user_id'), 'agent_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_tasks_user_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_next_run_at'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_enabled'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    # ### end Alembic commands ###
