"""daily review add care

Revision ID: e33f64acf851
Revises: db88b5cfcf7b
Create Date: 2026-06-12 22:06:01.913662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33f64acf851'
down_revision: Union[str, None] = 'db88b5cfcf7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reviews', sa.Column('care', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_reviews', 'care')
    # ### end Alembic commands ###
